# Generated by Django 3.1.4 on 2020-12-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
