# Generated by Django 3.1.2 on 2020-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='maxquantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
